/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finsys;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author pc1
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jSplitPane1 = new javax.swing.JSplitPane();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem_uom = new javax.swing.JMenuItem();
        jMenuItem_category = new javax.swing.JMenuItem();
        jMenuItem_item = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_issue = new javax.swing.JMenuItem();
        jMenuItem_essential = new javax.swing.JMenuItem();
        jMenuItem_store = new javax.swing.JMenuItem();
        jMenuItem_account = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_itemwise = new javax.swing.JMenuItem();
        jMenuItem_itemwisecc = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FINSYS - 1.0");
        setExtendedState(6);
        setLocationByPlatform(true);
        setName("frame_dashboard"); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu6.setText("Master");

        jMenuItem_uom.setText("Unit of measurement (UOM)");
        jMenuItem_uom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_uomActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem_uom);

        jMenuItem_category.setText("Item_category");
        jMenu6.add(jMenuItem_category);

        jMenuItem_item.setText("Item type");
        jMenu6.add(jMenuItem_item);

        jMenuBar1.add(jMenu6);

        jMenu2.setText("Report");

        jMenuItem_issue.setText("Issue Report");
        jMenu2.add(jMenuItem_issue);

        jMenuItem_essential.setText("Essential Report");
        jMenu2.add(jMenuItem_essential);

        jMenuItem_store.setText("Store Ledger");
        jMenu2.add(jMenuItem_store);

        jMenuItem_account.setText("Account wise store consumption");
        jMenu2.add(jMenuItem_account);

        jMenu5.setText("Item wise");

        jMenuItem_itemwise.setText("Item wise store consumption");
        jMenu5.add(jMenuItem_itemwise);

        jMenuItem_itemwisecc.setText("Item wise cost center consumption");
        jMenu5.add(jMenuItem_itemwisecc);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("FINSYS - 1.0");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_uomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_uomActionPerformed
        JFrame unit=new uom();
        Container c=getContentPane();
        c.removeAll();
        unit.setBounds(5,5,500,500);
        unit.setVisible(true);
        c.add(unit);
    }//GEN-LAST:event_jMenuItem_uomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem_account;
    private javax.swing.JMenuItem jMenuItem_category;
    private javax.swing.JMenuItem jMenuItem_essential;
    private javax.swing.JMenuItem jMenuItem_issue;
    private javax.swing.JMenuItem jMenuItem_item;
    private javax.swing.JMenuItem jMenuItem_itemwise;
    private javax.swing.JMenuItem jMenuItem_itemwisecc;
    private javax.swing.JMenuItem jMenuItem_store;
    private javax.swing.JMenuItem jMenuItem_uom;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("shivbari-23x23.png"))); 
    }
}
